"""Transpile KSB AST to Python 3 source."""

from __future__ import annotations

import re
from typing import Iterable

from ksb.ast_nodes import (
    Assign,
    Attr,
    BinOp,
    Break,
    Call,
    Continue,
    Expr,
    ExprStmt,
    FnDef,
    ForEach,
    If,
    Import,
    Index,
    Lambda,
    ListLit,
    Literal,
    MapLit,
    Match,
    MatchArm,
    Module,
    Name,
    Pat,
    PatBind,
    PatList,
    PatLiteral,
    PatMap,
    PatWildcard,
    Pipe,
    Return,
    Stmt,
    UnaryOp,
    While,
)
from ksb.errors import CodegenError

PY_RESERVED = {
    "False",
    "None",
    "True",
    "and",
    "as",
    "assert",
    "async",
    "await",
    "break",
    "class",
    "continue",
    "def",
    "del",
    "elif",
    "else",
    "except",
    "finally",
    "for",
    "from",
    "global",
    "if",
    "import",
    "in",
    "is",
    "lambda",
    "nonlocal",
    "not",
    "or",
    "pass",
    "raise",
    "return",
    "try",
    "while",
    "with",
    "yield",
}

BIN_PY = {
    "+": "+",
    "-": "-",
    "*": "*",
    "/": "/",
    "%": "%",
    "==": "==",
    "!=": "!=",
    "<": "<",
    ">": ">",
    "<=": "<=",
    ">=": ">=",
    "&&": "and",
    "||": "or",
}

RUNTIME_MODULES = frozenset(
    {
        "fs",
        "http",
        "json",
        "sh",
        "env",
        "log",
        "time",
        "path",
        "cli",
        "tool",
        "str",
    }
)

_INTERP_RE = re.compile(r"\{([A-Za-z_][A-Za-z0-9_]*)\}")


class Codegen:
    def __init__(self) -> None:
        self.lines: list[str] = []
        self.indent = 0
        self.imports: set[str] = set()
        self.needs_main = False
        self._match_id = 0
        self._helpers: list[str] = []  # complete helper function source blocks

    def generate(self, mod: Module) -> str:
        self.lines = []
        self.indent = 0
        self.imports = set()
        self.needs_main = False
        self._match_id = 0
        self._helpers = []

        for stmt in mod.body:
            if isinstance(stmt, Import):
                self.imports.add(stmt.module)
            if isinstance(stmt, FnDef) and stmt.name == "main":
                self.needs_main = True

        body_lines: list[str] = []
        saved = self.lines
        self.lines = body_lines
        for stmt in mod.body:
            if isinstance(stmt, Import):
                continue
            self._stmt(stmt)
        self.lines = saved

        self._emit("# generated by ksb — do not edit by hand")
        self._emit("from __future__ import annotations")
        self._emit("from ksb.runtime.ksb_rt import _attr")
        for m in sorted(self.imports):
            if m not in RUNTIME_MODULES:
                raise CodegenError(
                    "E20",
                    f"unknown module '{m}' (known: {', '.join(sorted(RUNTIME_MODULES))})",
                    line=0,
                    col=0,
                    path=mod.path,
                )
            self._emit(f"from ksb.runtime.ksb_rt import {m}")
        self._emit("")

        for h in self._helpers:
            self.lines.append(h.rstrip())
            self._emit("")

        self.lines.extend(body_lines)

        if self.needs_main:
            self._emit("")
            self._emit("if __name__ == '__main__':")
            self.indent += 1
            self._emit("_r = main()")
            self._emit("if _r is not None:")
            self.indent += 1
            self._emit("print(_r)")
            self.indent -= 2

        return "\n".join(self.lines).rstrip() + "\n"

    def _emit(self, line: str = "") -> None:
        if line:
            self.lines.append("    " * self.indent + line)
        else:
            self.lines.append("")

    def _ident(self, name: str) -> str:
        if name in PY_RESERVED:
            return f"_ksb_{name}"
        return name

    def _block(self, stmts: Iterable[Stmt]) -> None:
        stmts = list(stmts)
        if not stmts:
            self._emit("pass")
            return
        for s in stmts:
            self._stmt(s)

    def _stmt(self, s: Stmt) -> None:
        if isinstance(s, Assign):
            self._emit(f"{self._ident(s.name)} = {self._expr(s.value)}")
        elif isinstance(s, Return):
            if s.value is None:
                self._emit("return")
            else:
                self._emit(f"return {self._expr(s.value)}")
        elif isinstance(s, If):
            self._emit(f"if {self._expr(s.cond)}:")
            self.indent += 1
            self._block(s.then_body)
            self.indent -= 1
            if s.else_body is not None:
                self._emit("else:")
                self.indent += 1
                self._block(s.else_body)
                self.indent -= 1
        elif isinstance(s, While):
            self._emit(f"while {self._expr(s.cond)}:")
            self.indent += 1
            self._block(s.body)
            self.indent -= 1
        elif isinstance(s, ForEach):
            self._emit(f"for {self._ident(s.var)} in {self._expr(s.iter)}:")
            self.indent += 1
            self._block(s.body)
            self.indent -= 1
        elif isinstance(s, Break):
            self._emit("break")
        elif isinstance(s, Continue):
            self._emit("continue")
        elif isinstance(s, Match):
            # statement match: inline if/elif so assigns touch enclosing scope
            self._emit_match_inline(s)
        elif isinstance(s, ExprStmt):
            self._emit(self._expr(s.expr))
        elif isinstance(s, FnDef):
            params = ", ".join(self._ident(p) for p, _ in s.params)
            self._emit(f"def {self._ident(s.name)}({params}):")
            self.indent += 1
            self._block(s.body)
            self.indent -= 1
            self._emit("")
        else:
            raise CodegenError("E21", f"unsupported stmt {type(s).__name__}")

    def _expr(self, e: Expr | None) -> str:
        if e is None:
            return "None"
        if isinstance(e, Match):
            fn = self._emit_match_helper(e)
            return f"{fn}({self._expr(e.scrut)})"
        if isinstance(e, Name):
            return self._ident(e.id)
        if isinstance(e, Literal):
            return self._literal(e)
        if isinstance(e, ListLit):
            return "[" + ", ".join(self._expr(x) for x in e.elts) + "]"
        if isinstance(e, MapLit):
            parts = [f"{k!r}: {self._expr(v)}" for k, v in e.entries]
            return "{" + ", ".join(parts) + "}"
        if isinstance(e, BinOp):
            op = BIN_PY.get(e.op)
            if op is None:
                raise CodegenError("E22", f"unknown op {e.op}", line=e.line, col=e.col)
            return f"({self._expr(e.left)} {op} {self._expr(e.right)})"
        if isinstance(e, UnaryOp):
            if e.op == "!":
                return f"(not {self._expr(e.expr)})"
            if e.op == "-":
                return f"(-{self._expr(e.expr)})"
            raise CodegenError("E22", f"unknown unary {e.op}", line=e.line, col=e.col)
        if isinstance(e, Call):
            args = ", ".join(self._expr(a) for a in e.args)
            return f"{self._expr(e.func)}({args})"
        if isinstance(e, Index):
            return f"{self._expr(e.target)}[{self._expr(e.index)}]"
        if isinstance(e, Attr):
            # dict-friendly: data.n works for JSON maps and objects
            return f"_attr({self._expr(e.target)}, {e.attr!r})"
        if isinstance(e, Pipe):
            # x | f  => f(x)
            # x | f(a) => f(x, a)  — insert as first arg
            right = e.right
            left = self._expr(e.left)
            if isinstance(right, Name):
                return f"{self._ident(right.id)}({left})"
            if isinstance(right, Attr):
                return f"{self._expr(right)}({left})"
            if isinstance(right, Call):
                args = ", ".join([left] + [self._expr(a) for a in right.args])
                return f"{self._expr(right.func)}({args})"
            raise CodegenError(
                "E23",
                "pipe right side must be name, attr, or call",
                line=e.line,
                col=e.col,
            )
        if isinstance(e, Lambda):
            return self._lambda(e)
        raise CodegenError("E24", f"unsupported expr {type(e).__name__}", line=e.line, col=e.col)

    # --- match / patterns ---

    def _emit_match_inline(self, m: Match) -> None:
        """Inline if/elif match (statement form — binds/assigns stay local)."""
        self._match_id += 1
        subj = f"_m{self._match_id}"
        self._emit(f"{subj} = {self._expr(m.scrut)}")
        first = True
        for arm in m.arms:
            assert arm.pat is not None
            cond = self._pat_test(arm.pat, subj)
            kw = "if" if first else "elif"
            first = False
            self._emit(f"{kw} {cond}:")
            self.indent += 1
            for line in self._pat_binds(arm.pat, subj):
                self._emit(line)
            # strip trailing Return(None)-style from expr arms: for stmt match,
            # bare `pat => expr` was wrapped as Return — treat as expr stmt instead
            body = self._stmt_match_body(arm.body)
            self._block(body)
            self.indent -= 1
        self._emit("else:")
        self.indent += 1
        self._emit('raise ValueError("ksb: match failed")')
        self.indent -= 1

    def _stmt_match_body(self, body: list[Stmt]) -> list[Stmt]:
        """For statement match, `pat => expr` (stored as Return) → ExprStmt."""
        if len(body) == 1 and isinstance(body[0], Return) and body[0].value is not None:
            r = body[0]
            return [ExprStmt(expr=r.value, line=r.line, col=r.col)]
        return body

    def _emit_match_helper(self, m: Match) -> str:
        """Build `def _ksb_match_N(_m): ...` for expression-position match."""
        self._match_id += 1
        name = f"_ksb_match_{self._match_id}"
        saved_lines, saved_indent = self.lines, self.indent
        self.lines = []
        self.indent = 0
        self._emit(f"def {name}(_m):")
        self.indent += 1
        first = True
        for arm in m.arms:
            assert arm.pat is not None
            cond = self._pat_test(arm.pat, "_m")
            kw = "if" if first else "elif"
            first = False
            self._emit(f"{kw} {cond}:")
            self.indent += 1
            for line in self._pat_binds(arm.pat, "_m"):
                self._emit(line)
            self._block(arm.body)
            self._emit("return None")
            self.indent -= 1
        self._emit('raise ValueError("ksb: match failed")')
        self.indent -= 1
        helper_src = "\n".join(self.lines)
        self.lines, self.indent = saved_lines, saved_indent
        self._helpers.append(helper_src)
        return name

    def _pat_test(self, pat: Pat, subj: str) -> str:
        if isinstance(pat, PatWildcard):
            return "True"
        if isinstance(pat, PatBind):
            return "True"
        if isinstance(pat, PatLiteral):
            return f"({subj} == {self._lit_py(pat.value, pat.kind)})"
        if isinstance(pat, PatList):
            parts = [f"isinstance({subj}, (list, tuple))"]
            n = len(pat.elts)
            if pat.rest is None:
                parts.append(f"len({subj}) == {n}")
            else:
                parts.append(f"len({subj}) >= {n}")
            for i, el in enumerate(pat.elts):
                parts.append(self._pat_test(el, f"{subj}[{i}]"))
            return "(" + " and ".join(parts) + ")"
        if isinstance(pat, PatMap):
            parts = [f"isinstance({subj}, dict)"]
            for k, p in pat.entries:
                parts.append(f"({k!r} in {subj})")
                parts.append(self._pat_test(p, f"{subj}[{k!r}]"))
            return "(" + " and ".join(parts) + ")"
        raise CodegenError("E26", f"unknown pattern {type(pat).__name__}")

    def _pat_binds(self, pat: Pat, subj: str) -> list[str]:
        if isinstance(pat, PatWildcard):
            return []
        if isinstance(pat, PatLiteral):
            return []
        if isinstance(pat, PatBind):
            return [f"{self._ident(pat.name)} = {subj}"]
        if isinstance(pat, PatList):
            out: list[str] = []
            for i, el in enumerate(pat.elts):
                out.extend(self._pat_binds(el, f"{subj}[{i}]"))
            if pat.rest is not None:
                n = len(pat.elts)
                out.append(f"{self._ident(pat.rest)} = list({subj}[{n}:])")
            return out
        if isinstance(pat, PatMap):
            out = []
            for k, p in pat.entries:
                out.extend(self._pat_binds(p, f"{subj}[{k!r}]"))
            return out
        raise CodegenError("E26", f"unknown pattern {type(pat).__name__}")

    def _lit_py(self, value: object, kind: str) -> str:
        if kind == "bool":
            return "True" if value else "False"
        if kind == "null":
            return "None"
        if kind == "str":
            return repr(value)
        return repr(value)

    def _literal(self, e: Literal) -> str:
        if e.kind == "str":
            s = str(e.value)
            # simple "hi {name}" -> f"hi {name}"
            if _INTERP_RE.search(s) and "{" in s:
                # escape braces that aren't simple idents — keep simple
                def repl(m: re.Match[str]) -> str:
                    return "{" + self._ident(m.group(1)) + "}"

                body = _INTERP_RE.sub(repl, s.replace("{", "{{").replace("}", "}}"))
                # undo double-brace around idents: we broke it; redo cleanly
                body = str(e.value)

                def repl2(m: re.Match[str]) -> str:
                    return "{" + self._ident(m.group(1)) + "}"

                # convert to f-string carefully
                out: list[str] = []
                i = 0
                while i < len(body):
                    if body[i] == "{" and (m := _INTERP_RE.match(body, i)):
                        out.append("{" + self._ident(m.group(1)) + "}")
                        i = m.end()
                    elif body[i] in "{}":
                        out.append(body[i] * 2)
                        i += 1
                    else:
                        out.append(body[i])
                        i += 1
                inner = "".join(out).replace("\\", "\\\\").replace('"', '\\"')
                # rebuild without over-escaping braces we already doubled
                # simpler approach:
                return self._fstring(str(e.value))
            return repr(s)
        if e.kind == "bool":
            return "True" if e.value else "False"
        if e.kind == "null":
            return "None"
        return repr(e.value)

    def _fstring(self, s: str) -> str:
        parts: list[str] = ['f"']
        i = 0
        while i < len(s):
            ch = s[i]
            if ch == "{":
                m = _INTERP_RE.match(s, i)
                if m:
                    parts.append("{" + self._ident(m.group(1)) + "}")
                    i = m.end()
                    continue
                parts.append("{{")
                i += 1
                continue
            if ch == "}":
                parts.append("}}")
                i += 1
                continue
            if ch == "\\":
                parts.append("\\\\")
                i += 1
                continue
            if ch == '"':
                parts.append('\\"')
                i += 1
                continue
            if ch == "\n":
                parts.append("\\n")
                i += 1
                continue
            parts.append(ch)
            i += 1
        parts.append('"')
        return "".join(parts)

    def _lambda(self, e: Lambda) -> str:
        p = self._ident(e.param)
        body = e.body
        if isinstance(body, list):
            # multi-stmt -> nested def via helper is heavy; use exec-style not allowed
            # emit a local function expression via (lambda: ...) only for single return
            if len(body) == 1 and isinstance(body[0], Return):
                return f"(lambda {p}: {self._expr(body[0].value)})"
            if len(body) == 1 and isinstance(body[0], ExprStmt):
                return f"(lambda {p}: {self._expr(body[0].expr)})"
            raise CodegenError(
                "E25",
                "multi-statement lambda body not supported in MVP (use single expr)",
                line=e.line,
                col=e.col,
            )
        return f"(lambda {p}: {self._expr(body)})"


def transpile(mod: Module) -> str:
    return Codegen().generate(mod)


def compile_source(source: str, *, path: str | None = None, bundle: bool = True) -> str:
    """Parse (+ optional local-module bundle) and transpile to Python."""
    from pathlib import Path

    from ksb.modules import bundle_module, load_bundle
    from ksb.parser import parse

    if bundle and path and path not in ("<eval>", "<stdin>"):
        p = Path(path)
        if p.is_file() or source is not None:
            # use source text with path for resolution
            mod = parse(source, path=path)
            if p.exists():
                mod = bundle_module(mod, p)
            return transpile(mod)
    if bundle and path and Path(path).is_file() and source is None:
        return transpile(load_bundle(Path(path)))
    return transpile(parse(source, path=path))
